// <auto-generated />
using System;
using DiveDeep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiveDeep.Migrations
{
    [DbContext(typeof(DiveDeepContext))]
    [Migration("20260918082328_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiveDeep.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ActiveRents")
                        .HasColumnType("int");

                    b.Property<int?>("CompletedRents")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookingId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DiveDeep.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("BookingId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PackageId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DiveDeep.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1,
                            Amount = 5,
                            Category = "BCD",
                            Description = "Let og komfortabel BCD med god pasform og stabilitet, velegnet til både begyndere og erfarne dykkere.",
                            Image = "/Content/Images/Equipment/BCD/NavigatorLite.png",
                            Price = 125,
                            Title = "Scubapro Navigator Lite BCD"
                        },
                        new
                        {
                            EquipmentId = 2,
                            Amount = 5,
                            Category = "BCD",
                            Description = "En SCUBAPRO Glide BCD kombinerer komfort, stabilitet og nem opdriftskontrol. Det frontjusterbare design, Y-Fit-skuldre og integrerede vægtsystem sikrer en stabil og behagelig pasform under hele dykket.",
                            Image = "/Content/Images/Equipment/BCD/GlideBCD.png",
                            Price = 140,
                            Title = "Scubapro BCD Glide"
                        },
                        new
                        {
                            EquipmentId = 3,
                            Amount = 5,
                            Category = "BCD",
                            Description = "SCUBAPRO Hydros Pro er en avanceret BCD med et fleksibelt og modulært design, der giver høj komfort, stabilitet og præcis opdriftskontrol under dykket.",
                            Image = "/Content/Images/Equipment/BCD/HydrosPro.png",
                            Price = 200,
                            Title = "Scubapro BCD Hydros Pro"
                        },
                        new
                        {
                            EquipmentId = 4,
                            Amount = 5,
                            Category = "BCD",
                            Description = "SEAC Modular BCD er designet med fokus på fleksibilitet, komfort og stabilitet. Det modulære design giver en god pasform og gør den velegnet til både rekreativ dykning og forskellige dykkersituationer.",
                            Image = "/Content/Images/Equipment/BCD/Modular.png",
                            Price = 145,
                            Title = "Seac BCD Modular"
                        },
                        new
                        {
                            EquipmentId = 5,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "SCUBAPRO Definition er en 3 mm våddragt designet til høj komfort og bevægelsesfrihed. Det fleksible neoprenmateriale giver god pasform og hjælper med at holde kroppen varm under dykket.",
                            Image = "/Content/Images/Equipment/Divingsuits/Wetsuits/Definition.png",
                            Price = 100,
                            Title = "Scubapro Definition"
                        },
                        new
                        {
                            EquipmentId = 6,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "SCUBAPRO Definition er en 5 mm våddragt, der kombinerer varmeisolering, komfort og bevægelsesfrihed. Det fleksible neoprenmateriale sikrer en behagelig pasform og god beskyttelse mod koldt vand.",
                            Image = "/Content/Images/Equipment/Divingsuits/Wetsuits/Definition.png",
                            Price = 100,
                            Title = "Scubapro Definition"
                        },
                        new
                        {
                            EquipmentId = 7,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "SCUBAPRO Definition er en 7 mm våddragt designet til dykning i koldere vand. Det tykkere neopren giver effektiv varmeisolering, mens den fleksible konstruktion sikrer god komfort og bevægelsesfrihed under dykket.",
                            Image = "/Content/Images/Equipment/Divingsuits/Wetsuits/Definition.png",
                            Price = 100,
                            Title = "Scubapro Definition"
                        },
                        new
                        {
                            EquipmentId = 8,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "Waterproof W5 er en 3,5 mm våddragt, der kombinerer god varmeisolering med fleksibilitet og komfort. Det elastiske neoprenmateriale giver en behagelig pasform og god bevægelsesfrihed under dykket.",
                            Image = "/Content/Images/Equipment/Divingsuits/Wetsuits/W5.png",
                            Price = 100,
                            Title = "Waterproof W5"
                        },
                        new
                        {
                            EquipmentId = 9,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "Fourth Element Proteus er en 5 mm våddragt designet til effektiv varmeisolering og høj komfort. Det fleksible neoprenmateriale giver god bevægelsesfrihed og en tæt, behagelig pasform under dykket.",
                            Image = "/Content/Images/Equipment/Divingsuits/Wetsuits/ProteusF.png",
                            Price = 120,
                            Title = "Fourth Element Proteus"
                        },
                        new
                        {
                            EquipmentId = 10,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "SCUBAPRO Exodry 4.0 er en robust tørdragt designet til dykning i koldt vand. Den vandtætte konstruktion hjælper med at holde dig tør og varm, mens den komfortable pasform giver god bevægelsesfrihed under dykket.",
                            Image = "/Content/Images/Equipment/Divingsuits/Drysuits/Exodry4.png",
                            Price = 300,
                            Title = "Scubapro Exodry 4.0"
                        },
                        new
                        {
                            EquipmentId = 11,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "Waterproof D7 Evo er en slidstærk tørdragt designet til krævende dykning i koldt vand. Den vandtætte konstruktion giver effektiv beskyttelse mod vand, mens det fleksible design sikrer god komfort og bevægelsesfrihed under dykket.",
                            Image = "/Content/Images/Equipment/Divingsuits/Drysuits/D7Evo.png",
                            Price = 320,
                            Title = "Waterproof D7 Evo"
                        },
                        new
                        {
                            EquipmentId = 12,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "SANTI E.Lite Plus er en let og slidstærk tørdragt designet til komfortabel dykning under forskellige forhold. Den robuste konstruktion beskytter mod vand, mens det fleksible materiale giver god bevægelsesfrihed og komfort under dykket.",
                            Image = "/Content/Images/Equipment/Divingsuits/Drysuits/ELitePlus.png",
                            Price = 350,
                            Title = "Santi E.Lite Plus"
                        },
                        new
                        {
                            EquipmentId = 13,
                            Amount = 5,
                            Category = "Tanke",
                            Description = "SCUBAPRO 5 liters dykkertank er en kompakt og robust flaske, der er velegnet til kortere dyk og som ekstra luftforsyning. Den er nem at håndtere og transportere.",
                            Image = "/Content/Images/Equipment/Tanks/Tank.png",
                            Price = 150,
                            Title = "Scubapro 5 liter"
                        },
                        new
                        {
                            EquipmentId = 14,
                            Amount = 5,
                            Category = "Tanke",
                            Description = "SCUBAPRO 10 liters dykkertank er en robust og alsidig flaske med god luftkapacitet til både rekreative og længere dyk. Det kompakte design gør den nem at håndtere og transportere.",
                            Image = "/Content/Images/Equipment/Tanks/Tank.png",
                            Price = 160,
                            Title = "Scubapro 10 liter"
                        },
                        new
                        {
                            EquipmentId = 15,
                            Amount = 5,
                            Category = "Tanke",
                            Description = "SCUBAPRO 12 liters dykkertank er en robust flaske med høj luftkapacitet, velegnet til længere rekreative dyk. Den solide konstruktion sikrer pålidelig ydeevne og gør tanken velegnet til forskellige dykkeforhold.",
                            Image = "/Content/Images/Equipment/Tanks/Tank.png",
                            Price = 170,
                            Title = "Scubapro 12 liter"
                        },
                        new
                        {
                            EquipmentId = 16,
                            Amount = 5,
                            Category = "Tanke",
                            Description = "SCUBAPRO 15 liters dykkertank er en robust flaske med stor luftkapacitet, ideel til længere dyk og dykkere med et højt luftforbrug. Den solide konstruktion sikrer pålidelighed og stabilitet under dykket.",
                            Image = "/Content/Images/Equipment/Tanks/Tank.png",
                            Price = 180,
                            Title = "Scubapro 15 liter"
                        },
                        new
                        {
                            EquipmentId = 17,
                            Amount = 5,
                            Category = "Regulatorsæt",
                            Description = "SCUBAPRO Octopus R105/MK25EVO/S600 er et komplet regulatorsæt med høj ydeevne og pålidelig luftlevering. Sættet er designet til komfortabel vejrtrækning og stabil funktion under forskellige dykkeforhold.",
                            Image = "/Content/Images/Equipment/Regulator/MK25EVO.png",
                            Price = 125,
                            Title = "Scubapro Octopus R105/MK25EVO/S600"
                        },
                        new
                        {
                            EquipmentId = 18,
                            Amount = 5,
                            Category = "Regulatorsæt",
                            Description = "SCUBAPRO Octopus R095/MK17EVO/C370 er et pålideligt regulatorsæt, der giver en jævn og komfortabel luftlevering under dykket. Det robuste design sikrer stabil ydeevne og gør sættet velegnet til rekreativ dykning.",
                            Image = "/Content/Images/Equipment/Regulator/MK17.png",
                            Price = 100,
                            Title = "Scubapro Octopus R095/MK17EVO/C370"
                        },
                        new
                        {
                            EquipmentId = 19,
                            Amount = 5,
                            Category = "Regulatorsæt",
                            Description = "SCUBAPRO Octopus S270/MK25EVO BT/A700 Carbon BT er et avanceret regulatorsæt med høj ydeevne og jævn luftlevering. Det robuste design og materialer i høj kvalitet sikrer komfortabel vejrtrækning og pålidelig funktion under dykket.",
                            Image = "/Content/Images/Equipment/Regulator/MK25EVObt.png",
                            Price = 150,
                            Title = "Scubapro Octopus S270/MK25EVO BT/A700 Carbon BT"
                        },
                        new
                        {
                            EquipmentId = 20,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "SCUBAPRO Ghost er en komfortabel dykkermaske med lav volumen og et bredt synsfelt. Den tætsluttende silikonefacial giver en behagelig pasform og sikrer klart udsyn under vandet.",
                            Image = "/Content/Images/Equipment/Masks/Ghost.png",
                            Price = 50,
                            Title = "Scubapro Ghost"
                        },
                        new
                        {
                            EquipmentId = 21,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "SCUBAPRO D-Mask er en komfortabel dykkermaske med et moderne design og bredt synsfelt. Den bløde silikonefacial sikrer en tæt og behagelig pasform, mens det hærdede glas giver klart udsyn under vandet.",
                            Image = "/Content/Images/Equipment/Masks/DMask.png",
                            Price = 60,
                            Title = "Scubapro D-Mask"
                        },
                        new
                        {
                            EquipmentId = 22,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "SCUBAPRO Spectra Mini er en kompakt og komfortabel dykkermaske designet til mindre ansigter. Det brede synsfelt og den bløde silikonefacial sikrer klart udsyn og en tæt, behagelig pasform under vandet.",
                            Image = "/Content/Images/Equipment/Masks/SpectraMini.png",
                            Price = 50,
                            Title = "Scubapro Spectra Mini"
                        },
                        new
                        {
                            EquipmentId = 23,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "SCUBAPRO Crystal VU er en komfortabel dykkermaske med stort synsfelt og fremragende udsyn under vandet. Den bløde silikonefacial sikrer en tæt og behagelig pasform, mens det robuste glas giver et klart og naturligt udsyn.",
                            Image = "/Content/Images/Equipment/Masks/CrystalVu.png",
                            Price = 75,
                            Title = "Scubapro Crystal VU"
                        },
                        new
                        {
                            EquipmentId = 24,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "Fourth Element Scout Kontrast er en komfortabel dykkermaske designet til klart og præcist udsyn under vandet. Det kontrastfremhævende design og den tætsluttende silikonefacial giver god pasform og komfort under dykket.",
                            Image = "/Content/Images/Equipment/Masks/Scout.png",
                            Price = 75,
                            Title = "Fourth Element Scout Kontrast"
                        },
                        new
                        {
                            EquipmentId = 25,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Masks/ScoutEnchance.png",
                            Price = 75,
                            Title = "Fourth Element Scout Enchance"
                        },
                        new
                        {
                            EquipmentId = 26,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "TUSA Element er en komfortabel dykkermaske med et enkelt og funktionelt design. Den bløde silikonefacial sikrer en tæt pasform, mens det klare glas giver et godt og naturligt udsyn under vandet.",
                            Image = "/Content/Images/Equipment/Masks/Element.png",
                            Price = 75,
                            Title = "Tusa Element"
                        },
                        new
                        {
                            EquipmentId = 27,
                            Amount = 5,
                            Category = "Finner",
                            Description = "SCUBAPRO Jet Fin er en robust og klassisk dykkerfinne med et kraftfuldt design, der giver effektiv fremdrift og god kontrol i vandet. Den solide konstruktion gør den velegnet til både rekreativ og krævende dykning.",
                            Image = "/Content/Images/Equipment/Fins/JetFin.png",
                            Price = 50,
                            Title = "Scubapro Jet Fin"
                        },
                        new
                        {
                            EquipmentId = 28,
                            Amount = 5,
                            Category = "Finner",
                            Description = "SCUBAPRO GO Travel er en let og kompakt dykkerfinne designet til rejser og nem transport. Det fleksible design giver god fremdrift og komfort, samtidig med at finnerne er nemme at pakke og tage med på farten.",
                            Image = "/Content/Images/Equipment/Fins/TravelFins.png",
                            Price = 50,
                            Title = "Scubapro GO travel"
                        },
                        new
                        {
                            EquipmentId = 29,
                            Amount = 5,
                            Category = "Finner",
                            Description = "SCUBAPRO Seawing Supernova er en kraftfuld dykkerfinne med innovativt design, der giver effektiv fremdrift og god kontrol i vandet. Den fleksible konstruktion sikrer en behagelig og energieffektiv svømning under dykket.",
                            Image = "/Content/Images/Equipment/Fins/SeawingSupernova.png",
                            Price = 60,
                            Title = "Scubapro Seawing Supernova"
                        },
                        new
                        {
                            EquipmentId = 30,
                            Amount = 5,
                            Category = "Finner",
                            Description = "SEAC Propulsion er en kraftfuld dykkerfinne designet til effektiv fremdrift og god kontrol i vandet. Den robuste og fleksible konstruktion giver komfortabel svømning og stabil ydeevne under dykket.",
                            Image = "/Content/Images/Equipment/Fins/Propulsion.png",
                            Price = 50,
                            Title = "Seac Propulsion"
                        },
                        new
                        {
                            EquipmentId = 31,
                            Amount = 5,
                            Category = "Finner",
                            Description = "SEAC ALA er en let og komfortabel dykkerfinne designet til effektiv fremdrift og god manøvredygtighed. Den fleksible konstruktion giver en behagelig svømmeoplevelse og stabil kontrol under dykket.",
                            Image = "/Content/Images/Equipment/Fins/ALA.png",
                            Price = 50,
                            Title = "Seac ALA"
                        },
                        new
                        {
                            EquipmentId = 32,
                            Amount = 5,
                            Category = "Finner",
                            Description = "Fourth Element Tech er en robust dykkerfinne designet til teknisk dykning og krævende forhold. Den stive konstruktion giver kraftfuld fremdrift, præcis kontrol og effektiv svømning under vandet.",
                            Image = "/Content/Images/Equipment/Fins/TechFins.png",
                            Price = 75,
                            Title = "Fourth Element Tech"
                        },
                        new
                        {
                            EquipmentId = 33,
                            Amount = 5,
                            Category = "Finner",
                            Description = "Fourth Element Rec Fin er en alsidig og komfortabel dykkerfinne designet til rekreativ dykning. Den fleksible konstruktion giver effektiv fremdrift, god kontrol og en behagelig svømmeoplevelse under vandet.",
                            Image = "/Content/Images/Equipment/Fins/RecFins.png",
                            Price = 80,
                            Title = "Fourth Element Rec Fin"
                        });
                });

            modelBuilder.Entity("DiveDeep.Models.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Sizes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageId");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            Amount = 5,
                            Category = "Pakke",
                            Equipment = "[\"BCD\",\"Dykkerdragt\",\"Regulators\\u00E6t\",\"Tank\",\"Finner\",\"Maske\",\"Snorkel\"]",
                            Image = "/Content/Images/Packages/Package1.png",
                            Price = 750,
                            Title = "Komplet dykkersæt"
                        },
                        new
                        {
                            PackageId = 2,
                            Amount = 5,
                            Category = "Pakke",
                            Equipment = "[\"Finner\",\"Maske\",\"Snorkel\"]",
                            Image = "/Content/Images/Packages/Package2.png",
                            Price = 100,
                            Title = "Komplet snorkelsæt"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.Booking", b =>
                {
                    b.HasOne("DiveDeep.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("Bookings")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("DiveDeep.Models.CartItem", b =>
                {
                    b.HasOne("DiveDeep.Models.Booking", "Booking")
                        .WithMany("CartItems")
                        .HasForeignKey("BookingId");

                    b.HasOne("DiveDeep.Models.Equipment", "Equipment")
                        .WithMany("CartItems")
                        .HasForeignKey("EquipmentId");

                    b.HasOne("DiveDeep.Models.Package", "Package")
                        .WithMany("CartItems")
                        .HasForeignKey("PackageId");

                    b.Navigation("Booking");

                    b.Navigation("Equipment");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DiveDeep.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DiveDeep.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiveDeep.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DiveDeep.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Data.ApplicationUser", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DiveDeep.Models.Booking", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("DiveDeep.Models.Equipment", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("DiveDeep.Models.Package", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
