// <auto-generated />
using System;
using DiveDeep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiveDeep.Migrations
{
    [DbContext(typeof(DiveDeepContext))]
    partial class DiveDeepContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiveDeep.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ActiveRents")
                        .HasColumnType("int");

                    b.Property<int?>("CompletedRents")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookingId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DiveDeep.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("BookingId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PackageId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DiveDeep.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1,
                            Amount = 5,
                            Category = "BCD",
                            Description = "TEMP",
                            Image = "/Content/Images/Equipment/BCD/NavigatorLite.png",
                            Price = 125,
                            Title = "Scubapro Navigator Lite BCD"
                        },
                        new
                        {
                            EquipmentId = 2,
                            Amount = 5,
                            Category = "BCD",
                            Description = "TEMP",
                            Image = "/Content/Images/Equipment/BCD/GlideBCD.png",
                            Price = 140,
                            Title = "Scubapro BCD Glide"
                        },
                        new
                        {
                            EquipmentId = 3,
                            Amount = 5,
                            Category = "BCD",
                            Description = "TEMP",
                            Image = "/Content/Images/Equipment/BCD/HydrosPro.png",
                            Price = 200,
                            Title = "Scubapro BCD Hydros Pro"
                        },
                        new
                        {
                            EquipmentId = 4,
                            Amount = 5,
                            Category = "BCD",
                            Description = "TEMP",
                            Image = "/Content/Images/Equipment/BCD/Modular.png",
                            Price = 145,
                            Title = "Seac BCD Modular"
                        },
                        new
                        {
                            EquipmentId = 5,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "Våddragt, 3 mm",
                            Image = "/Content/Images/Equipment/Divingsuits/Wetsuits/Definition.png",
                            Price = 100,
                            Title = "Scubapro Definition"
                        },
                        new
                        {
                            EquipmentId = 6,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "Våddragt, 5 mm",
                            Image = "/Content/Images/Equipment/Divingsuits/Wetsuits/Definition.png",
                            Price = 100,
                            Title = "Scubapro Definition"
                        },
                        new
                        {
                            EquipmentId = 7,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "Våddragt, 7 mm",
                            Image = "/Content/Images/Equipment/Divingsuits/Wetsuits/Definition.png",
                            Price = 100,
                            Title = "Scubapro Definition"
                        },
                        new
                        {
                            EquipmentId = 8,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "Våddragt, 3.5 mm",
                            Image = "/Content/Images/Equipment/Divingsuits/Wetsuits/W5.png",
                            Price = 100,
                            Title = "Waterproof W5"
                        },
                        new
                        {
                            EquipmentId = 9,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "Våddragt, 5 mm",
                            Image = "/Content/Images/Equipment/Divingsuits/Wetsuits/ProteusF.png",
                            Price = 120,
                            Title = "Fourth Element Proteus"
                        },
                        new
                        {
                            EquipmentId = 10,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "Tørdragt",
                            Image = "/Content/Images/Equipment/Divingsuits/Drysuits/Exodry4.png",
                            Price = 300,
                            Title = "Scubapro Exodry 4.0"
                        },
                        new
                        {
                            EquipmentId = 11,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "Tørdragt",
                            Image = "/Content/Images/Equipment/Divingsuits/Drysuits/D7Evo.png",
                            Price = 320,
                            Title = "Waterproof D7 Evo"
                        },
                        new
                        {
                            EquipmentId = 12,
                            Amount = 5,
                            Category = "Dykkerdragt",
                            Description = "Tørdragt",
                            Image = "/Content/Images/Equipment/Divingsuits/Drysuits/ELitePlus.png",
                            Price = 350,
                            Title = "Santi E.Lite Plus"
                        },
                        new
                        {
                            EquipmentId = 13,
                            Amount = 5,
                            Category = "Tanke",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Tanks/Tank.png",
                            Price = 150,
                            Title = "Scubapro 5 liter"
                        },
                        new
                        {
                            EquipmentId = 14,
                            Amount = 5,
                            Category = "Tanke",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Tanks/Tank.png",
                            Price = 160,
                            Title = "Scubapro 10 liter"
                        },
                        new
                        {
                            EquipmentId = 15,
                            Amount = 5,
                            Category = "Tanke",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Tanks/Tank.png",
                            Price = 170,
                            Title = "Scubapro 12 liter"
                        },
                        new
                        {
                            EquipmentId = 16,
                            Amount = 5,
                            Category = "Tanke",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Tanks/Tank.png",
                            Price = 180,
                            Title = "Scubapro 15 liter"
                        },
                        new
                        {
                            EquipmentId = 17,
                            Amount = 5,
                            Category = "Regulatorsæt",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Regulator/MK25EVO.png",
                            Price = 125,
                            Title = "Scubapro Octopus R105/MK25EVO/S600"
                        },
                        new
                        {
                            EquipmentId = 18,
                            Amount = 5,
                            Category = "Regulatorsæt",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Regulator/MK17.png",
                            Price = 100,
                            Title = "Scubapro Octopus R095/MK17EVO/C370"
                        },
                        new
                        {
                            EquipmentId = 19,
                            Amount = 5,
                            Category = "Regulatorsæt",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Regulator/MK25EVObt.png",
                            Price = 150,
                            Title = "Scubapro Octopus S270/MK25EVO BT/A700 Carbon BT"
                        },
                        new
                        {
                            EquipmentId = 20,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Masks/Ghost.png",
                            Price = 50,
                            Title = "Scubapro Ghost"
                        },
                        new
                        {
                            EquipmentId = 21,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Masks/DMask.png",
                            Price = 60,
                            Title = "Scubapro D-Mask"
                        },
                        new
                        {
                            EquipmentId = 22,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Masks/SpectraMini.png",
                            Price = 50,
                            Title = "Scubapro Spectra Mini"
                        },
                        new
                        {
                            EquipmentId = 23,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Masks/CrystalVu.png",
                            Price = 75,
                            Title = "Scubapro Crystal VU"
                        },
                        new
                        {
                            EquipmentId = 24,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Masks/Scout.png",
                            Price = 75,
                            Title = "Fourth Element Scout Kontrast"
                        },
                        new
                        {
                            EquipmentId = 25,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Masks/ScoutEnchance.png",
                            Price = 75,
                            Title = "Fourth Element Scout Enchance"
                        },
                        new
                        {
                            EquipmentId = 26,
                            Amount = 5,
                            Category = "Maske/Snorkel",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Masks/Element.png",
                            Price = 75,
                            Title = "Tusa Element"
                        },
                        new
                        {
                            EquipmentId = 27,
                            Amount = 5,
                            Category = "Finner",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Fins/JetFin.png",
                            Price = 50,
                            Title = "Scubapro Jet Fin"
                        },
                        new
                        {
                            EquipmentId = 28,
                            Amount = 5,
                            Category = "Finner",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Fins/TravelFins.png",
                            Price = 50,
                            Title = "Scubapro GO travel"
                        },
                        new
                        {
                            EquipmentId = 29,
                            Amount = 5,
                            Category = "Finner",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Fins/SeawingSupernova.png",
                            Price = 60,
                            Title = "Scubapro Seawing Supernova"
                        },
                        new
                        {
                            EquipmentId = 30,
                            Amount = 5,
                            Category = "Finner",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Fins/Propulsion.png",
                            Price = 50,
                            Title = "Seac Propulsion"
                        },
                        new
                        {
                            EquipmentId = 31,
                            Amount = 5,
                            Category = "Finner",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Fins/ALA.png",
                            Price = 50,
                            Title = "Seac ALA"
                        },
                        new
                        {
                            EquipmentId = 32,
                            Amount = 5,
                            Category = "Finner",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Fins/TechFins.png",
                            Price = 75,
                            Title = "Fourth Element Tech"
                        },
                        new
                        {
                            EquipmentId = 33,
                            Amount = 5,
                            Category = "Finner",
                            Description = "N/A",
                            Image = "/Content/Images/Equipment/Fins/RecFins.png",
                            Price = 80,
                            Title = "Fourth Element Rec Fin"
                        });
                });

            modelBuilder.Entity("DiveDeep.Models.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageId");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            Amount = 5,
                            Category = "Pakke",
                            Equipment = "[\"BCD\",\"Dykkerdragt\",\"Regulators\\u00E6t\",\"Tank\",\"Finner\",\"Maske\",\"Snorkel\"]",
                            Image = "/Content/Images/Packages/Package1.png",
                            Price = 750,
                            Title = "Komplet dykkersæt"
                        },
                        new
                        {
                            PackageId = 2,
                            Amount = 5,
                            Category = "Pakke",
                            Equipment = "[\"Finner\",\"Maske\",\"Snorkel\"]",
                            Image = "/Content/Images/Packages/Package2.png",
                            Price = 100,
                            Title = "Komplet snorkelsæt"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DiveDeep.Models.Booking", b =>
                {
                    b.HasOne("DiveDeep.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("Bookings")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("DiveDeep.Models.CartItem", b =>
                {
                    b.HasOne("DiveDeep.Models.Booking", "Booking")
                        .WithMany("CartItems")
                        .HasForeignKey("BookingId");

                    b.HasOne("DiveDeep.Models.Equipment", "Equipment")
                        .WithMany("CartItems")
                        .HasForeignKey("EquipmentId");

                    b.HasOne("DiveDeep.Models.Package", "Package")
                        .WithMany("CartItems")
                        .HasForeignKey("PackageId");

                    b.Navigation("Booking");

                    b.Navigation("Equipment");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DiveDeep.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DiveDeep.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiveDeep.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DiveDeep.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeep.Data.ApplicationUser", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DiveDeep.Models.Booking", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("DiveDeep.Models.Equipment", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("DiveDeep.Models.Package", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
