<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\Content\Images\DiveDeepLogo.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Content\Images\Divingsuits\Drysuits\" />
    <Folder Include="wwwroot\Content\Images\Regulator\" />
    <Folder Include="wwwroot\Content\Images\Tanks\" />
  </ItemGroup>

</Project>
